name: foundry_ds
description: "A production-grade Flutter design system inspired by OpenAI's aesthetic. Provides comprehensive tokens, semantic layers, and reusable components."
version: 0.0.3
homepage: https://github.com/lfbardi-don/foundry_ds
repository: https://github.com/lfbardi-don/foundry_ds

environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1
  lucide_icons_flutter: ^3.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Bold.ttf
          weight: 700
